spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb
    username: postgres
    password: 2004
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8090